name: data_processor
description: Flexible command-line data processor.
version: 1.0.0
homepage: https://github.com/andyduke/data_processor_cli
publish_to: 'none'

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependencies: 
  liquid_engine: ^0.2.2
  jmespath: ^2.0.1
  args: ^2.3.0
  io: ^1.0.3
  json2yaml: ^3.0.0
  yaml: ^3.1.0
  pretty_json: ^2.0.0
  yaml_writer:
    git: https://github.com/andyduke/yaml_writer.git
  csv: ^5.0.1
  toml: ^0.12.0
  xml_map_converter: ^1.0.0+1
  markdown_ansi_renderer:
    git:
      url: https://github.com/andyduke/markdown_ansi_renderer.git
      path: package
  markdown: ^4.0.1
  barbecue: ^0.4.0

dependency_overrides:
  yaml_writer:
    path: ../local_packages/yaml_writer
  markdown_ansi_renderer:
    path: ../../markdown_ansi_renderer/package
