name: data_processor
description: Flexible command-line data processor.
version: 1.0.0
# homepage: https://www.example.com
publish_to: 'none'

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependencies: 
  liquid_engine: ^0.2.2
  jmespath:
    path: ../local_packages/jmespath
  args: ^2.3.0
  io: ^1.0.3
  json2yaml: ^3.0.0
  yaml: ^3.1.0
  pretty_json: ^2.0.0
  #yaml_writer: ^1.0.1
  yaml_writer:
    path: ../local_packages/yaml_writer
  csv: ^5.0.1
  toml: ^0.12.0
  xml_map_converter:
    path: ../local_packages/xml_map_converter/package
  markdown_ansi_renderer:
    path: ../../markdown_ansi_renderer/package
